#! /bin/sh
# Test arbitrary --greeting.
# 
# Copyright (C) 2001, 2006 Free Software Foundation, Inc.  
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

trap 'rm -fr $tmpfiles' 1 2 3 15

LANGUAGE=
LC_ALL=
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

tmpfiles="greeting-test1.ok"
cat <<EOF > greeting-test1.ok
Nothing happens here.
EOF

tmpfiles="$tmpfiles greeting-test1.out"
: ${HELLO=hello}
${HELLO} -g 'Nothing happens here.' > greeting-test1.out

: ${DIFF=diff}
${DIFF} greeting-test1.ok greeting-test1.out
result=$?

rm -f $tmpfiles

exit $result
