#! /bin/sh
# Test that last greeting option specified is what counts.
#
# Copyright 2013 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
# This script takes one argument.

trap 'rm -fr $tmpfiles' 1 2 3 15

# We force the C locale here, since we are checking normal output,
# which will be translated.

LANGUAGE=
LC_ALL=C
LC_MESSAGES=
LANG=
export LANGUAGE LC_ALL LC_MESSAGES LANG

tmpfiles="multiline-box-test1.ok"
cat <<EOF > multiline-box-test1.ok
+----------+
| abcd     |
| 1	23 |
+----------+
EOF

tmpfiles="$tmpfiles multiline-box-test1.out"
: ${HELLO=hello}
${HELLO} -n -g "$(printf abcd\\n1\\t23\\n)" | tr -d '\r' \
| tr -d '\r' >multiline-box-test1.out

: ${DIFF=diff}
${DIFF} multiline-box-test1.ok multiline-box-test1.out
result=$?

rm -fr $tmpfiles

exit $result
