\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename hello.info
@include version.texi
@settitle GNU Hello @value{VERSION}
@c %**end of header

@copying
This manual is for GNU Hello (version @value{VERSION}, @value{UPDATED}),
which prints a friendly greeting (and serves as an example GNU package).

Copyright (C) 1992, 1993, 1996, 2002, 2005 Free Software Foundation,
Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@dircategory Basics
@direntry
* Hello: (hello).               Hello, GNU world.
@end direntry

@titlepage
@title GNU Hello
@subtitle for version @value{VERSION}, @value{UPDATED}
@author GNU Hello Development Team (@email{bug-texinfo@@gnu.org})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top GNU Hello

This manual is for GNU Hello (version @value{VERSION}, @value{UPDATED}).
@end ifnottex

@menu
* Instructions::	How to read this manual. 
* Overview::		Preliminary information.
* Sample::		Sample output from @code{hello}.
* Invoking hello::	How to run @code{hello}.
* Problems::		Reporting bugs.
* Copying This Manual:: Copying and sharing this documentation.
* Concept Index::	Index of concepts.
@end menu

@node Instructions
@chapter How to Read This Manual

@cindex reading
@cindex manual, how to read
@cindex how to read
To read this manual, begin at the beginning, reading from left to right
and top to bottom, until you get to the end.  Then stop.  You may pause
anywhere in the middle as well, if you wish.

@node Overview
@chapter Overview
@cindex greetings
@cindex overview

The GNU @code{hello} program produces a familiar, friendly greeting.
It allows nonprogrammers to use a classic computer science tool which
would otherwise be unavailable to them.  Because it is protected by the
GNU General Public License, users are free to share and change it.

GNU @code{hello} was written by Mike Haertel, David MacKenzie, Jan
Brittenson, Charles Hannum, Roland McGrath, Noah Friedman, Karl
Eichwalder, and @w{The King}.

@node Sample
@chapter Sample Output
@cindex sample

Here are some realistic examples of running GNU @code{hello}.

This is the output of the command @samp{hello}:

@example
Hello, world!
@end example

This is the output of the command @samp{hello --help}:

@example
This is GNU Hello, THE greeting printing program.
Usage: hello [OPTION]
  -h, --help          display this help and exit
  -v, --version       display version information and exit
  -t, --traditional   use traditional greeting format
  -m, --mail          print your mail

Report bugs to bug-gnu-hello@@gnu.org.
@end example

This is the output of the command @samp{hello --traditional}:

@example
hello, world
@end example

@node Invoking hello, Problems, Sample, Top
@chapter Invoking @code{hello}
@cindex invoking
@cindex version
@cindex options
@cindex usage
@cindex help
@cindex getting help

The format for running the @code{hello} program is:

@example
hello @var{option} @dots{}
@end example

@code{hello} supports the following options:

@table @samp
@item --help
@itemx -h
Print an informative help message describing the options and then exit.

@item --version
@itemx -v
Print the version number of @code{hello} on the standard error output
and then exit.

@item --traditional
@itemx -t
@cindex traditional
@cindex modern
Use the traditional greeting message @samp{hello, world} rather 
than the more modern @samp{Hello, world!}.

@item --mail
@itemx -m
@cindex mail
@cindex creeping feature
@cindex feature, creeping
@cindex feeping creature
@cindex creature, feeping
Print your mail on the standard output.
@end table

@node Problems
@chapter Reporting Bugs
@cindex bugs
@cindex problems

To report bugs or suggest enhancements for GNU @code{hello}, please
send electronic mail to @email{bug-hello@@gnu.org}.

Include the version number, which you can find by running
@w{@samp{hello --version}}.  Also include in your message the output
that the program produced and the output you expected.


@node Copying This Manual
@appendix Copying This Manual

@menu
* GNU Free Documentation License::  License for copying this manual.
@end menu

@include fdl.texi


@node Concept Index
@unnumbered Concept Index

@cindex tail recursion
@printindex cp

@bye
